jwt:
  secret:
    access: "w7uGmFxgOlFS9T+gFynHk7jB6mI/eA9WgjG5o9gB8uI=w7uGmFxgOlFS9T+gFynHk7jB6mI/eA9WgjG5o9gB8uI="
    refresh: "w7uGmFxgOlFS9T+gFynHk7jB6mI/eA9WgjG5o9gB8uI=w7uGmFxgOlFS9T+gFynHk7jB6mI/eA9WgjG5o9gB8uI="

spring:
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console
  #      settings:
  #        web-allow-others: true
  #
  #  datasource:
  #    url: jdbc:h2:mem:testdb
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password:

  # 환경변수를 통해 설정하는 대신, 테스트용으로 직접 값을 지정합니다.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/mydatabase       # 테스트용 DB URL (실제 테스트 환경에 맞게 수정)
    username: dbuser                                  # 테스트용 DB 사용자
    password: dbpassword                              # 테스트용 DB 비밀번호
    hikari:
      maximum-pool-size: 20                           # 커넥션 풀 최대 크기

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "33440475191-u35mrt8q9aqtr3d5fqr9b29udiktlpkp.apps.googleusercontent.com"
            client-secret: "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"
            scope: profile,email

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
